"""
modal_bootstrap.py — Hardened Modal app provisioning.

Handles token resolution, app file generation, deployment, URL extraction,
and teardown. Single entry point for all Modal GPU work in this project.

Usage:
    from modal_bootstrap import deploy_vllm_app, stop_app, list_apps
    info = await deploy_vllm_app(gpu="H100", model="Qwen/Qwen3-30B-A3B")
    print(info.endpoint_url)
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import subprocess
import textwrap
from dataclasses import dataclass
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

ENV_FILE = Path("C:/Users/keith/dev/.env")
MODAL_APPS_DIR = Path(__file__).parent / "modal_apps"
STATE_FILE = Path(__file__).parent / ".modal_state.json"

# Map our friendly GPU names → Modal GPU slugs
GPU_SLUG_MAP = {
    # Friendly name variants an agent might pass
    "t4":        "T4",
    "l4":        "L4",
    "a10":       "A10",
    "a10g":      "A10",
    "l40s":      "L40S",
    "a100":      "A100-80GB",
    "a100-40gb": "A100-40GB",
    "a100-80gb": "A100-80GB",
    "h100":      "H100",
    "h200":      "H200",
    "b200":      "B200",
}


# ── Return type ───────────────────────────────────────────────────────────────

@dataclass
class ModalInstanceInfo:
    app_id: str
    app_name: str
    endpoint_url: str       # HTTPS web endpoint — OpenAI-compatible base
    gpu: str
    model: str
    status: str = "deployed"

    @property
    def openai_base_url(self) -> str:
        return self.endpoint_url.rstrip("/")

    @property
    def connection_summary(self) -> str:
        return (
            f"Modal app: {self.app_name}\n"
            f"GPU:       {self.gpu}\n"
            f"Model:     {self.model}\n"
            f"Endpoint:  {self.endpoint_url}\n"
            f"OpenAI base URL: {self.openai_base_url}\n"
            f"Test: curl {self.endpoint_url}/health"
        )


# ── State ─────────────────────────────────────────────────────────────────────

def _load_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except Exception:
            pass
    return {}


def _save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


# ── Token resolution ──────────────────────────────────────────────────────────

def resolve_modal_env() -> dict[str, str]:
    """
    Returns env dict with MODAL_TOKEN_ID and MODAL_TOKEN_SECRET set.
    Priority: current process env → .env file → error.
    """
    token_id = os.environ.get("MODAL_TOKEN_ID")
    token_secret = os.environ.get("MODAL_TOKEN_SECRET")

    if not token_id or not token_secret:
        if ENV_FILE.exists():
            for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
                if line.startswith("MODAL_TOKEN_ID="):
                    token_id = line.split("=", 1)[1].strip()
                elif line.startswith("MODAL_TOKEN_SECRET="):
                    token_secret = line.split("=", 1)[1].strip()

    if not token_id or not token_secret:
        raise RuntimeError(
            "Modal credentials not found.\n"
            "Set MODAL_TOKEN_ID and MODAL_TOKEN_SECRET in C:/Users/keith/dev/.env\n"
            "Or run: modal token set --token-id ak-... --token-secret as-..."
        )

    return {**os.environ, "MODAL_TOKEN_ID": token_id, "MODAL_TOKEN_SECRET": token_secret}


def normalize_gpu(gpu: str) -> str:
    """Convert user-facing GPU names to Modal slugs."""
    return GPU_SLUG_MAP.get(gpu.lower(), gpu)


# ── App file generation ───────────────────────────────────────────────────────

def _generate_app_file(app_name: str, gpu_slug: str, model_id: str) -> Path:
    """
    Writes a Modal app Python file to modal_apps/{app_name}.py.
    Returns the path.
    """
    MODAL_APPS_DIR.mkdir(exist_ok=True)

    # Escape model_id for embedding in Python string
    safe_model = model_id.replace('"', '\\"')
    safe_app   = app_name.replace('"', '\\"')

    code = textwrap.dedent(f'''\
        """
        Auto-generated Modal vLLM app.
        GPU: {gpu_slug}  Model: {model_id}
        Generated by gpu-skill-builder/modal_bootstrap.py
        """
        import modal

        app = modal.App("{safe_app}")

        vllm_image = (
            modal.Image.from_registry("vllm/vllm-openai:latest", add_python="3.11")
            # vllm/vllm-openai image has a vllm entrypoint; clear it so Modal can
            # start its Python worker process normally.
            .entrypoint([])
            .pip_install("httpx", "fastapi")
        )


        @app.cls(
            gpu="{gpu_slug}",
            image=vllm_image,
            timeout=3600,
            min_containers=1,
        )
        @modal.concurrent(max_inputs=100)
        class VLLMServer:
            model_id: str = "{safe_model}"

            @modal.enter()
            def start_vllm(self):
                import subprocess, time, httpx

                cmd = [
                    "vllm", "serve", self.model_id,
                    "--host", "127.0.0.1",
                    "--port", "8000",
                    "--gpu-memory-utilization", "0.88",
                    "--enable-prefix-caching",
                    "--language-model-only",
                    "--served-model-name", self.model_id,
                ]
                self._proc = subprocess.Popen(cmd)

                # Wait up to 4 minutes for vLLM to be ready
                for _ in range(120):
                    try:
                        r = httpx.get("http://127.0.0.1:8000/health", timeout=2)
                        if r.status_code == 200:
                            return
                    except Exception:
                        pass
                    time.sleep(2)
                raise RuntimeError(f"vLLM failed to start for model {{self.model_id}}")

            @modal.asgi_app()
            def serve(self):
                import httpx
                from fastapi import FastAPI, Request
                from fastapi.responses import StreamingResponse

                proxy = FastAPI(title=f"vLLM proxy — {{self.model_id}}")

                @proxy.api_route(
                    "/{{path:path}}",
                    methods=["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"],
                )
                async def forward(request: Request, path: str):
                    async with httpx.AsyncClient(timeout=180) as client:
                        resp = await client.request(
                            request.method,
                            f"http://127.0.0.1:8000/{{path}}",
                            headers={{
                                k: v for k, v in request.headers.items()
                                if k.lower() not in ("host", "content-length")
                            }},
                            content=await request.body(),
                            params=dict(request.query_params),
                        )
                    return StreamingResponse(
                        content=resp.aiter_bytes(),
                        status_code=resp.status_code,
                        media_type=resp.headers.get("content-type", "application/json"),
                    )

                return proxy
    ''')

    app_file = MODAL_APPS_DIR / f"{app_name}.py"
    app_file.write_text(code, encoding="utf-8")
    return app_file


# ── Deploy ────────────────────────────────────────────────────────────────────

async def deploy_vllm_app(
    gpu: str = "H100",
    model: str = "Qwen/Qwen3-30B-A3B",
    app_name: str | None = None,
) -> ModalInstanceInfo:
    """
    Idempotent. Deploys a Modal vLLM app and returns endpoint info.
    If an app with this name is already deployed, returns the existing one.
    """
    gpu_slug = normalize_gpu(gpu)
    if app_name is None:
        safe_gpu = gpu_slug.lower().replace("-", "")
        app_name = f"gpu-skill-{safe_gpu}"

    # Idempotency: check state file
    state = _load_state()
    existing = state.get("apps", {}).get(app_name)
    if existing and existing.get("endpoint_url"):
        print(f"Modal app '{app_name}' already deployed. Reusing.")
        return ModalInstanceInfo(**existing)

    print(f"Generating Modal app '{app_name}' ({gpu_slug}, {model})...")
    app_file = _generate_app_file(app_name, gpu_slug, model)

    print("Deploying to Modal (this builds the container image on first run ~2-3 min)...")
    env = resolve_modal_env()

    # Force UTF-8 in the subprocess so Modal's emoji output doesn't crash on Windows cp1252
    deploy_env = {**env, "PYTHONUTF8": "1", "PYTHONIOENCODING": "utf-8", "NO_COLOR": "1"}

    proc = await asyncio.create_subprocess_exec(
        "modal", "deploy", str(app_file),
        env=deploy_env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    output = stdout.decode(errors="replace") + stderr.decode(errors="replace")

    if proc.returncode != 0:
        raise RuntimeError(
            f"modal deploy failed (exit {proc.returncode}):\n{output}"
        )

    # Safe print — Modal output contains emoji/box-drawing that cp1252 can't encode
    safe_output = output.encode("ascii", errors="replace").decode("ascii")
    print(safe_output)

    endpoint_url = _extract_endpoint_url(output)
    if not endpoint_url:
        # Fallback: look it up via SDK
        endpoint_url = await _lookup_endpoint_url(app_name, env)

    if not endpoint_url:
        raise RuntimeError(
            f"Deployment succeeded but could not determine endpoint URL.\n"
            f"Deploy output:\n{output}"
        )

    app_id = _extract_app_id(output) or app_name

    info = ModalInstanceInfo(
        app_id=app_id,
        app_name=app_name,
        endpoint_url=endpoint_url,
        gpu=gpu_slug,
        model=model,
        status="deployed",
    )

    # Persist
    apps = state.get("apps", {})
    apps[app_name] = {
        "app_id": info.app_id,
        "app_name": info.app_name,
        "endpoint_url": info.endpoint_url,
        "gpu": info.gpu,
        "model": info.model,
        "status": info.status,
    }
    state["apps"] = apps
    _save_state(state)

    return info


# ── Stop ──────────────────────────────────────────────────────────────────────

async def stop_app(app_name: str) -> None:
    """Stops a deployed Modal app by name."""
    env = resolve_modal_env()
    proc = await asyncio.create_subprocess_exec(
        "modal", "app", "stop", "--yes", app_name,
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    if proc.returncode != 0:
        raise RuntimeError(
            f"modal app stop failed: {stderr.decode()}"
        )
    print(f"Stopped Modal app '{app_name}'")

    state = _load_state()
    state.get("apps", {}).pop(app_name, None)
    _save_state(state)


# ── List ──────────────────────────────────────────────────────────────────────

async def list_apps() -> list[dict]:
    """Returns list of deployed Modal apps from state file."""
    state = _load_state()
    return list(state.get("apps", {}).values())


# ── URL extraction helpers ────────────────────────────────────────────────────

def _extract_endpoint_url(deploy_output: str) -> str | None:
    """Parse the web endpoint URL from 'modal deploy' output."""
    # Modal deploy outputs lines like:
    #   => https://username--appname-vlllmserver-serve.modal.run
    match = re.search(r"https://[\w\-]+\.modal\.run", deploy_output)
    if match:
        return match.group(0)
    return None


def _extract_app_id(deploy_output: str) -> str | None:
    match = re.search(r"ap-[a-zA-Z0-9]+", deploy_output)
    return match.group(0) if match else None


async def _lookup_endpoint_url(app_name: str, env: dict) -> str | None:
    """Fallback: ask Modal SDK for the web URL after deployment."""
    # Try SDK lookup (Modal 1.4.2+: use Cls.from_name)
    try:
        import modal as _modal
        cls = _modal.Cls.from_name(app_name, "VLLMServer")
        url = cls().serve.get_web_url()
        if url and url.startswith("http"):
            return url
    except Exception:
        pass

    # Derive URL from known pattern: https://{workspace}--{app}-vllmserver-serve.modal.run
    # workspace = Modal account name (keith-harmon for this account)
    try:
        proc = await asyncio.create_subprocess_exec(
            "modal", "profile", "current",
            env=env,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        workspace = stdout.decode(errors="replace").strip().lower().replace(" ", "-").replace("_", "-")
        if workspace:
            return f"https://{workspace}--{app_name}-vllmserver-serve.modal.run"
    except Exception:
        pass

    return None
